SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM ThongTinThanhToanOnline;
DELETE FROM DonHangChiTiet;
DELETE FROM DonHang;
DELETE FROM GioHangChiTiet;
DELETE FROM AnhSP;
DELETE FROM GiaTriBienThe;
DELETE FROM GiaTriThongSo;
DELETE FROM BienThe;
DELETE FROM ThongSoBienTheMau;
DELETE FROM ThongSoMau;
DELETE FROM SanPham;
DELETE FROM LoaiSanPham;
DELETE FROM TaiKhoan;

-- Reset Auto Increment
ALTER TABLE LoaiSanPham AUTO_INCREMENT = 1;
ALTER TABLE SanPham AUTO_INCREMENT = 1;
ALTER TABLE BienThe AUTO_INCREMENT = 1;
ALTER TABLE ThongSoMau AUTO_INCREMENT = 1;
ALTER TABLE GiaTriThongSo AUTO_INCREMENT = 1;
ALTER TABLE AnhSP AUTO_INCREMENT = 1;
ALTER TABLE TaiKhoan AUTO_INCREMENT = 1;
ALTER TABLE DonHang AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;

SELECT 'Reset hoàn tất!' AS KetQua;